language: R
sudo: required
cache: packages
r_check_args: --no-manual

r_binary_packages:
  - checkmate
  - coda
  - ggplot2
  - magrittr
  - MASS
  - Rcpp
  - rlang
  - rstan
  - runjags
  - truncnorm
  - dplyr
  - knitr
  - numDeriv
  - polycor
  - purrr
  - reshape2
  - rmarkdown
  - roxygen2
  - shinystan
  - testthat

before_install:
  - sudo apt-get install jags

after_failure:
  - cat mpt2irt.Rcheck/00*

