language: R
sudo: required
cache: packages
r_check_args: --no-manual

r_packages:
  - rstan

r_binary_packages:
  - devtools
  - checkmate
  - coda
  - ggplot2
  - magrittr
  - MASS
  - Rcpp
  - rlang
  - runjags
  - truncnorm
  - dplyr
  - knitr
  - numDeriv
  - polycor
  - purrr
  - reshape2
  - rmarkdown
  - roxygen2
  - shinystan
  - testthat

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#     - os: linux
#       dist: trusty
#       r: devel
#       r_binary_packages:
#         - devtools
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#           packages:
#             - g++-7
#       env:
#         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#     - os: osx
#       fortran: true
#       osx_image: xcode10
#       r: release

before_install:
  - sudo apt-get install jags
  - mkdir -p ~/.R/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CXX14 = clang++ -arch x86_64 -ftemplate-depth-256" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CXX14FLAGS = -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-unknown-pragmas" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "CC = clang" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install inconsolata; fi

after_failure:
  - cat mpt2irt.Rcheck/00*
