# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_check_args: --no-manual

before_install:
  - sudo apt-get install jags

after_failure:
  - cat mpt2irt.Rcheck/00*

