# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
r: release
cache: packages


r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes

# r_github_packages:
#   - jimhester/covr

r_binary_packages: 
  - assertthat
  - base64enc
  - bitops
  - brew
  - caTools
  - checkmate
  - colorspace
  - dplyr
  - dichromat
  - highr
  - htmltools
  - labeling
  - lattice
  - magrittr
  - markdown
  - MASS
  - munsell
  - numDeriv
  - praise
  - purrr
  - RColorBrewer
  - reshape2
  - rmarkdown
  - scales
  - testthat
  - tidyr
  - truncnorm
  - tibble

env:
  matrix: 
    - CXX_OLEVEL=2 CXX=clang++

before_install:
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars 
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

script: 
  - |
    travis_wait R CMD build .
    travis_wait 60 R CMD check rstanarm*tar.gz

after_script:
  - tar -ztvf rstanarm_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - cat rstanarm.Rcheck/00*
