// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sample_pp
NumericVector sample_pp(NumericMatrix prob);
RcppExport SEXP _mpt2irt_sample_pp(SEXP probSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type prob(probSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_pp(prob));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mpt2irt_sample_pp", (DL_FUNC) &_mpt2irt_sample_pp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mpt2irt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
